# https://docs.travis-ci.com/user/languages/python/
language: python

python:
  - '3.6'
  - '2.7'

sudo: required

before_install:
- sudo apt install -y swig
- pip install cython
- pip install -r requirements.txt
- make
- ./scripts/download-test-data.sh

script:
- python inference.py
# TODO: add move tests
